import { Figtree } from "next/font/google";
import "./globals.css";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Skill Sage - online learning platform (template)",
  description: "Generated by xinov-bits (Tanishq)",
};

// COMPONENTS
import Header from '@/components/layouts/Header'
import Footer from "@/components/layouts/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
